server:
  port: 9671

spring:
  main:
    web-application-type: reactive
  application:
    name: gateway
  cloud:
    gateway:
      routes:
        - id: carts
          uri: lb://carts
          predicates:
            - Path=/carts/**
          filters:
            - StripPrefix=1
        - id: edit
          uri: lb://edit
          predicates:
            - Path=/edit/**
          filters:
            - StripPrefix=1
        - id: orders
          uri: lb://orders
          predicates:
            - Path=/orders/**
          filters:
            - StripPrefix=1
        - id: users
          uri: lb://users
          predicates:
            - Path=/users/**
          filters:
            - StripPrefix=1
        - id: view
          uri: lb://view
          predicates:
            - Path=/view/**
          filters:
            - StripPrefix=1
        - id: registry
          uri: lb://registry
          predicates:
            - Path=/registry/**
          filters:
            - StripPrefix=1
        - id: eureka
          uri: lb://registry
          predicates:
            - Path=/eureka/**

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
    healthcheck:
      enabled: true
  instance:
    preferIpAddress: true

management:
  endpoints:
    web:
      exposure:
        include: "*"